ktor:
  application:
    modules:
      - com.commerce.ApplicationKt.module
  deployment:
    port: 8080

jwt:
  secret: "secret"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to 'hello'"

database:
  url: "jdbc:h2:file:./data/orderdb;DB_CLOSE_DELAY=-1"
  user: "sa"
  password: ""
  driver: "org.h2.Driver"
